version: '2.3'

services:
  dynamodb:
     image: cnadiminti/dynamodb-local:latest
  admin:
      image: boogak/dynamodb-admin
      ports:
       - 8001:8001
      environment: 
        - DYNAMO_ENDPOINT=http://dynamodb:8000
  serverless:
    build: .
    ports:
     - 3000:4000
     - 9229:9229
    volumes:
      - .:/usr/src/app
    environment:
      # - DEBUG=*
      - AWS_REGION=localhost
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxx+
    command: yarn start
    links:
      - dynamodb
