service: tech-crunch-rss-reader-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  region: localhost
  profile: serverless-admin # Profile configured on credential file aws path /home/youruser/.aws
  stage: dev #prod test dev
  environment:
    IS_OFFLINE: 'true'
plugins:
  - serverless-offline
  - serverless-plugin-typescript
custom:
  serverless-offline:
    host: 0.0.0.0
    port: 4000
  stage: ${opt:stage, self:provider.stage}
  basePath: 'api'
functions:
  rss-reader:
    handler: posts/handlers/rss-reader.handler
    events:
      - http:
          path: ${self:custom.basePath}/posts
          method: get

    
