service: tech-crunch-rss-reader-api

package:
  exclude:
    - node_modules/serverless-offline/**

provider:
  profile: serverless-admin
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  region: us-east-1
  stage: test
  environment:
    TECH_CRUNCH_FEED_URL: 'http://feeds.feedburner.com/TechCrunch/'
plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 4000
  stage: ${opt:stage, self:provider.stage}

functions:
  rss-reader:
    handler: src/handlers/rss-reader.handler
    events:
      - http:
          path: api/posts
          method: get
          cors: true
              

    
